name: Vale Lint
on: [pull_request]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          filter_mode: nofilter
